apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: 're-dev'
  labels: {}
  annotations: {}
  namespace: re-dev
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: re-dev.c0749e2.kyma.ondemand.com
  service:
    name: re-dev
    port: 8080
  rules:
    - path: /.*
      methods:
        - GET
        - PUT
        - POST
        - DELETE
      accessStrategies:
        - handler: allow
